---
collections:
  - infra.aap_configuration
  - infra.aap_utilities
  - infra.controller_configuration
  - infra.eda_configuration
  - infra.ee_utilities
  - ansible.eda
  - ansible.hub
  - ansible.utils
# The following collections need to be downloaded manually
# from your private automation hub if intended to be used
# locally in a content creator environment
# - ansible-controller-4.6.11.tar.gz
#  - ansible.platform
#  - infra.aap_configuration_extended
